-- 재정공지 게시판
CREATE TABLE IF NOT EXISTS approval_notice_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  author TEXT DEFAULT '다애교회',
  post_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  hit_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS approval_notice_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES approval_notice_posts(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  original_name TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE approval_notice_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE approval_notice_files ENABLE ROW LEVEL SECURITY;

CREATE POLICY "approval_notice_posts_read" ON approval_notice_posts FOR SELECT USING (true);
CREATE POLICY "approval_notice_posts_admin" ON approval_notice_posts FOR ALL USING (true);
CREATE POLICY "approval_notice_files_read" ON approval_notice_files FOR SELECT USING (true);
CREATE POLICY "approval_notice_files_admin" ON approval_notice_files FOR ALL USING (true);
